print(['.source MPClass.jav....Object\n', 
'\n.method public st...([II)[I\n', 
'.var 0 is m [I from... Label1\n', 
'.var 1 is n I from ... Label1\n', 
'.var 2 is i I from ... Label1\n', 
'Label0:\n', '\ticonst_1\n', 
'\tistore_2\n', 'Label2:\n', 
'\tiload_2\n', '\tiload_1\n', 
'\tif_icmpgt Label4\n', 
'\taload_0\n\tiload_...n\tisub\n',
 '\tiload_2\n', ...])